### ISSUE TITLE
Error posting payload to check API endpoint followed by SIGALRM exception

### ISSUE THREAD

**Issue by rclagett** [Netuitive/netuitive-diamond#46]
SupervisorD kills and restarts the agent for an unknown reason. When the agent comes back online and tries to post a heartbeat check, it fails ending with a SIGALRM Exception. The agent, sans the heartbeat collector, continues running. This results in expired checks until the agent process is manually restarted. 

supervisord.log:

```
WARN received SIGTERM indicating exit request
INFO waiting for netuitive-agent, netuitive-statsd to die
INFO stopped: netuitive-statsd (terminated by SIGTERM)
INFO waiting for netuitive-agent to die
INFO waiting for netuitive-agent to die
INFO waiting for netuitive-agent to die
WARN killing 'netuitive-agent' (9507) with SIGKILL
INFO stopped: netuitive-agent (terminated by SIGKILL)
CRIT Supervisor running as root (no user in config file)
INFO RPC interface 'supervisor' initialized
CRIT Server 'unix_http_server' running without any HTTP authentication checking
INFO daemonizing the supervisord process
INFO supervisord started with pid 24353
INFO spawned: 'netuitive-agent' with pid 24356
INFO spawned: 'netuitive-statsd' with pid 24357
INFO success: netuitive-agent entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
INFO success: netuitive-statsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
```

netuitive-agent.log:

```
[MainThread:HeartbeatCollector:ERROR] error posting payload to api ingest endpoint (https://api.app.netuitive.com/check/apikey/heartbeat/element/150:
Traceback (most recent call last): 
File "/opt/netuitive-agent/embedded/lib/python2.7/site-packages/netuitive-0.3.0-py2.7.egg/netuitive/client.py", line 173, in post_check 
resp = urllib2.urlopen(request) 
File "/opt/netuitive-agent/embedded/lib/python2.7/urllib2.py", line 154, in urlopen 
return opener.open(url, data, timeout) 
File "/opt/netuitive-agent/embedded/lib/python2.7/urllib2.py", line 429, in open 
response = self._open(req, data) 
File "/opt/netuitive-agent/embedded/lib/python2.7/urllib2.py", line 447, in _open 
'_open', req) 
File "/opt/netuitive-agent/embedded/lib/python2.7/urllib2.py", line 407, in _call_chain 
result = func(*args) 
File "/opt/netuitive-agent/embedded/lib/python2.7/urllib2.py", line 1241, in https_open 
context=self._context) 
File "/opt/netuitive-agent/embedded/lib/python2.7/urllib2.py", line 1195, in do_open 
h.request(req.get_method(), req.get_selector(), req.data, headers) 
File "/opt/netuitive-agent/embedded/lib/python2.7/httplib.py", line 1042, in request 
self._send_request(method, url, body, headers) 
File "/opt/netuitive-agent/embedded/lib/python2.7/httplib.py", line 1082, in _send_request 
self.endheaders(body) 
File "/opt/netuitive-agent/embedded/lib/python2.7/httplib.py", line 1038, in endheaders 
self._send_output(message_body) 
File "/opt/netuitive-agent/embedded/lib/python2.7/httplib.py", line 882, in _send_output 
self.send(msg) 
File "/opt/netuitive-agent/embedded/lib/python2.7/httplib.py", line 844, in send 
self.connect() 
File "/opt/netuitive-agent/embedded/lib/python2.7/httplib.py", line 1255, in connect 
HTTPConnection.connect(self) 
File "/opt/netuitive-agent/embedded/lib/python2.7/httplib.py", line 821, in connect 
self.timeout, self.source_address) 
File "/opt/netuitive-agent/embedded/lib/python2.7/socket.py", line 566, in create_connection 
sock.connect(sa) 
File "/opt/netuitive-agent/embedded/lib/python2.7/socket.py", line 228, in meth 
return getattr(self._sock,name)(*args) 
File "/opt/netuitive-agent/embedded/lib/python2.7/site-packages/diamond/utils/signals.py", line 11, in signal_to_exception 
raise SIGALRMException() 
SIGALRMException
```

**Comment by rclagett** [comment]
supervisord.log:

```
WARN received SIGTERM indicating exit request
INFO waiting for netuitive-agent, netuitive-statsd to die
INFO stopped: netuitive-statsd (terminated by SIGTERM)
INFO waiting for netuitive-agent to die
INFO waiting for netuitive-agent to die
INFO waiting for netuitive-agent to die
WARN killing 'netuitive-agent' (9507) with SIGKILL
INFO stopped: netuitive-agent (terminated by SIGKILL)
CRIT Supervisor running as root (no user in config file)
INFO RPC interface 'supervisor' initialized
CRIT Server 'unix_http_server' running without any HTTP authentication checking
INFO daemonizing the supervisord process
INFO supervisord started with pid 24353
INFO spawned: 'netuitive-agent' with pid 24356
INFO spawned: 'netuitive-statsd' with pid 24357
INFO success: netuitive-agent entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
INFO success: netuitive-statsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
```

**Comment by yahonggu** [comment]
@rclagett  do you have the full log from supervisord and netuitive-agent so that I can look at the timestamps to correlate the message for the dirty killing?

**Comment by rclagett** [comment]
@yahonggu I do. I'll share in Jira because there may be sensitive data.

**Comment by rclagett** [comment]
Fixed by https://github.com/Netuitive/netuitive-diamond/pull/54.
